export default [
    {
      id: 1,
      name: "ستایش",
      lastName: "بنددار",
      phone: "09194162621",
      relation:"دوست",
      email: "setayeshbanddar7899@gmail.com",
    },
    {
        id: 2,
        name: "ستایش",
        lastName: "بنددار",
        phone: "09194162621",
        relation:"دوست",
        email: "setayeshbanddar7899@gmail.com",
      },
      {
        id: 3,
        name: "ستایش",
        lastName: "بنددار",
        phone: "09194162621",
        relation:"دوست",
        email: "setayeshbanddar7899@gmail.com",
      },
      {
        id: 4,
        name: "ستایش",
        lastName: "بنددار",
        phone: "09194162621",
        relation:"دوست",
        email: "setayeshbanddar7899@gmail.com",
      },
      {
        id: 5,
        name: "ستایش",
        lastName: "بنددار",
        phone: "09194162621",
        relation:"دوست",
        email: "setayeshbanddar7899@gmail.com",
      },
      {
        id: 6,
        name: "ستایش",
        lastName: "بنددار",
        phone: "09194162621",
        relation:"دوست",
        email: "setayeshbanddar7899@gmail.com",
      },
  ];